# Development docker-compose. Assuming the folders of BBF/API are in the folders
# relative to this repository, point /etc/hosts to river 127.0.0.1 and connect
# to http://river:88

version: '3.8'

services:
  traefik:
    image: traefik:v2.9.6
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
    ports:
      - "88:80"
      - "8088:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  river-api:
    build:
      context: ../river-api
    environment:
      - DB_HOST=astroriver-db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=psql
      - DB_NAME=postgres
      - DB_PREFIX=postgresql+asyncpg
      - ASTROCAST_API_KEY=${ASTROCAST_API_KEY}
      - ASTROCAST_API_URL=${ASTROCAST_API_URL}
    ports:
      - 8005:8000
    depends_on:
      - astroriver-db
    volumes:
      - ../river-api/app:/app/app

  astroriver-bff:
    build:
      context: ../astroriver-bff
    environment:
      - KEYCLOAK_CLIENT_ID=${KEYCLOAK_CLIENT_ID}
      - KEYCLOAK_BFF_ID=${KEYCLOAK_BFF_ID}
      - KEYCLOAK_BFF_SECRET=${KEYCLOAK_BFF_SECRET}
      - KEYCLOAK_REALM=${KEYCLOAK_REALM}
      - KEYCLOAK_URL=${KEYCLOAK_URL}
      - RIVER_API_URL=http://river-api:8000
    labels:
      - "traefik.http.routers.astroriver-bff.rule=Host(`river`) && PathPrefix(`/api`)"
      - "traefik.http.services.astroriver-bff.loadbalancer.server.port=8000"
    volumes:
      - ../astroriver-bff/app:/app/app
    entrypoint: ["uvicorn", "--host=0.0.0.0",
              "--timeout-keep-alive=0", "app.main:app", "--reload"]

  astroriver-ui:
    build:
      context: .
      dockerfile: Dockerfile.dev  # Uses the dockerfile containing yarn dev
    labels:
      - "traefik.http.routers.astroriver-ui.rule=Host(`river`)"
      - "traefik.http.services.astroriver-ui.loadbalancer.server.port=5173"
    volumes:
      - ../astroriver-ui:/app

  astroriver-db:
    image: postgres:16.1
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=psql
      - POSTGRES_DB=postgres
    ports:
      - 5433:5432
    volumes:
      - astroriver-db-data:/var/lib/postgresql/data

volumes:
  astroriver-db-data:
